spring:
  application:
    name: gateway

server:
  port: 8021

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka