spring:
  application:
    name: config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  profiles:
    active: native

server:
  port: 8017

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka